# Generated by Django 3.2.9 on 2022-06-16 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0013_auto_20220616_1424'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyniki', '0015_auto_20220223_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WynikiDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas', models.FloatField(default=0, verbose_name='Czas')),
                ('miss_value', models.FloatField(default=0, verbose_name='Miss')),
                ('procedura_value', models.FloatField(default=0, verbose_name='Procedura')),
                ('noshoot_value', models.FloatField(default=0, verbose_name='NoShoot')),
                ('wynik', models.FloatField(default=0, verbose_name='NoShoot')),
                ('result', models.TextField(default='0', max_length=60, null=True)),
                ('kara', models.CharField(choices=[('BRAK', 'BRAK'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DSQ', 'DSQ'), ('PK', 'PK')], default='BRAK', max_length=10)),
                ('oplata', models.BooleanField(default=False)),
                ('bron_klubowa', models.BooleanField(default=False, verbose_name='Broń klubowa')),
                ('amunicja_klubowa', models.BooleanField(default=False, verbose_name='Amunicja klubowa')),
                ('edited_by_sedzia', models.BooleanField(default=False)),
                ('zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.zawodydynamic', verbose_name='konkurencja')),
            ],
            options={
                'verbose_name_plural': 'Wyniki zawodów dynamicznych',
            },
        ),
    ]
