# Generated by Django 3.2.9 on 2022-06-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0016_wynikidynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wynikidynamic',
            name='miss_value',
            field=models.IntegerField(default=0, verbose_name='Miss'),
        ),
        migrations.AlterField(
            model_name='wynikidynamic',
            name='noshoot_value',
            field=models.IntegerField(default=0, verbose_name='NoShoot'),
        ),
        migrations.AlterField(
            model_name='wynikidynamic',
            name='procedura_value',
            field=models.IntegerField(default=0, verbose_name='Procedura'),
        ),
        migrations.AlterField(
            model_name='wynikidynamic',
            name='wynik',
            field=models.FloatField(default=0),
        ),
    ]
