# Generated by Django 3.2.9 on 2022-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0010_auto_20220428_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='turniej',
            name='turniej_archiwalny',
            field=models.BooleanField(default=False, verbose_name='Turniej archiwalny'),
        ),
    ]
