# Generated by Django 3.2.9 on 2022-06-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0011_turniej_turniej_archiwalny'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZawodyGrupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='zawody',
            name='zawody_grupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawody.zawodygrupa'),
        ),
    ]
