# Generated by Django 3.2.9 on 2022-06-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0012_auto_20220614_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='turniej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zawody.turniej'),
        ),
        migrations.AlterField(
            model_name='zawody',
            name='zawody_grupa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawody.zawodygrupa'),
        ),
        migrations.CreateModel(
            name='ZawodyDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('oplata_konkurencja', models.FloatField(default=0)),
                ('oplata_bron', models.FloatField(default=0)),
                ('oplata_amunicja', models.FloatField(default=0)),
                ('miss', models.IntegerField(default=0)),
                ('procedura', models.IntegerField(default=0)),
                ('noshoot', models.IntegerField(default=0)),
                ('turniej', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zawody.turniej')),
            ],
            options={
                'verbose_name_plural': 'Zawody dynamiczne',
            },
        ),
    ]
