# Generated by Django 3.2.9 on 2022-06-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zawody', '0013_auto_20220616_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zawody',
            options={'verbose_name_plural': 'Zawody statyczne'},
        ),
        migrations.CreateModel(
            name='SedziaDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sedzia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.zawodydynamic')),
            ],
            options={
                'verbose_name_plural': 'Sędziowie konkurencji dynamicznych',
            },
        ),
    ]
