# Generated by Django 3.2.9 on 2022-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0014_auto_20220616_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='turniej',
            name='wyniki_generalne_widoczne',
            field=models.BooleanField(default=True, verbose_name='Pokaż wyniki generalne'),
        ),
        migrations.AddField(
            model_name='turniej',
            name='wyniki_widoczne',
            field=models.BooleanField(default=True, verbose_name='Pokaż wyniki'),
        ),
    ]
