# Generated by Django 4.0.1 on 2022-08-25 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zawody', '0015_auto_20220621_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drużyny',
            },
        ),
        migrations.AddField(
            model_name='turniej',
            name='turniej_druzynowy',
            field=models.BooleanField(default=False, verbose_name='Turniej drużynowy'),
        ),
        migrations.CreateModel(
            name='ZawodnicyDruzyny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druzyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zawody.druzyna')),
                ('zawodnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skład drużyn',
            },
        ),
        migrations.AddField(
            model_name='druzyna',
            name='turniej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zawody.turniej'),
        ),
    ]
